name = "khatmat-darb-alzahra"
compatibility_date = "2026-05-22"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "khatmat_darb_alzahra"
database_id = "6487157c-bba1-40f4-8965-757fa6fb2708"
